feat: add health checks probes
janus-idp/helm-backstage pull request #119
Opened 2023-10-04 19:19 UTC by jesuino

## Description of the change

Adds the health check probes using the same value as the upstream commented probes:

https://github.com/backstage/charts/blob/main/charts/backstage/values.yaml#L162

This should be merged after https://github.com/janus-idp/backstage-showcase/pull/567

## Existing or Associated Issue(s)

https://github.com/janus-idp/backstage-showcase/issues/565

## Additional Information

This should fix the info dialog in Openshift, where it asks users to setup health checks

![openshift_healthcheck_warning](https://github.com/janus-idp/helm-backstage/assets/359820/33adc12b-8fff-46ec-8f5a-84a021f69646)

## Checklist

- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ ] Variables are documented in the `values.yaml` and added to the README.md. The [pre-commit](https://pre-commit.com/) utility can be used to generate the necessary content. Use `pre-commit run -a` to apply changes.
- [ ] JSON Schema template updated and re-generated the raw schema via `pre-commit` hook.
- [ ] List tests pass for Chart using the [Chart Testing](https://github.com/helm/chart-testing) tool and the `ct lint` command.

2023-10-24 13:28 UTC, tumido requested changes
@jesuino can you please rebase and update the version again? Please don't forget to run `pre-commit` to regenerate the `README.md`.

2023-10-24 21:47 UTC, tumido approved these changes
/lgtm
/approve

2023-10-24 21:48 UTC, tumido commented
Btw, @jesuino do you think this should be rather a patch or feature release? Your PR title suggests it should be a feature release however your chart version change is a patch release.

2023-10-25 17:04 UTC, jesuino commented
Hello @tumido I think a patch release is better suitable for this issue. Thanks for pointing this. I just fixed the conflicts with main branch

2023-11-01 12:33 UTC, tumido approved these changes
/lgtm
/approve

2023-11-01 12:33 UTC, merged